### ISSUE TITLE
Add verb validation to views endpoints

### ISSUE THREAD

**Issue by jsteuver** [RobBoeckermann/Meetify#26]
Currently, you can use any API verb (GET, POST, PUT, etc.) on almost every one of our endpoints and get the same result regardless of the verb. Typically, different verbs are used for different actions.

Should we add validation to our endpoints so that only specific verbs are supported?

**Comment by segeeslice** [comment]
Just to clarify, is this just saying that I can POST (update) or GET (receive) some set of data at the same URL? I think that's fine since the URL generally represents the data at hand, and the HTTP command should represent what to do with that data.

Otherwise, if I understand correctly, we would have something like...

>GET http://.../getUser

...which is conceptually redundant.

[This stack overflow blog](https://stackoverflow.blog/2020/03/02/best-practices-for-rest-api-design/) on REST API best practices backs this sentiment (under "**Use nouns instead of verbs in endpoint paths**")

**Comment by jsteuver** [comment]
> Just to clarify, is this just saying that I can POST (update) or GET (receive) some set of data at the same URL? I think that's fine since the URL generally represents the data at hand, and the HTTP command should represent what to do with that data.

What I was trying to say was we have _no separation of functionality_ for the different verbs on the same URL.

For example, both the `POST` and `GET` on the `/user/login` endpoint will perform the exact same thing: logging in the user and returning user information. _(This particular endpoint is a bad example because we probably only want it to do one thing anyway.)_

The issue, if we want to tackle it, is seemingly two-fold:

1. We need to route the request to different functions depending on the verb
2. If a verb is not acceptable on a particular endpoint, we need to error if that verb is used

The biggest question, though, is _do we want to tackle it?_ If this were a larger-scale REST API then yes, we absolutely should, but I am wondering if it is worth the effort needed to make this happen given our scope.

**Comment by segeeslice** [comment]
Ah, I see. I would think we need to support it in some sense, yes. In `/user/login`, it sort of makes sense to not care about which type, but I think cases of basic data manipulation would benefit from it, mainly because I don't see any cleaner alternative.

For example, if we wanted to utilize profile data for a user with pk 1234, something like `/users/1234/profile` should be the endpoint for both receiving and updating that profile via GET and POST.

I don't really think it's a question of difficulty in implementation either. From [this stack exchange](https://stackoverflow.com/questions/19096227/how-to-discriminate-based-on-http-method-in-django-urlpatterns), it appears to be a basic field in the `request` objects:

```py
def myview(request):
    if request.method == 'GET':
        # Code for GET requests
    elif request.method == 'POST':
        # Code for POST requests
```

**Comment by jsteuver** [comment]
Removing question label. This should be implemented.

**Comment by segeeslice** [comment]
@RobBoeckermann you may want to look over this discussion for further endpoints
