### ISSUE TITLE
Newlines are being deleted in messages

### ISSUE THREAD

**Issue by jsteuver** [RobBoeckermann/Meetify#47]
Discovered in #40 through integration testing.

When sending messages with newlines, the newlines are deleted. Not sure what is causing the issue exactly, but here are a few things that are worth checking:

- Format of the message text that is received by the server (and how it's parsed in the Django request)
- How Django handles saving strings with newlines to the database
- How strings with newlines are stored in the database

**Comment by jsteuver** [comment]
From what I've gathered, the problem is in how Django returns the messages after retrieving them from the database. The only solutions I have seen involve utilizing Django render filters, but we are treating Django as a REST API (and thus not rendering with it), so these solutions are useless to us.

There may be a way we can hack in line break escape characters when storing/retrieving messages, however. Definitely not the cleanest solution, but it may be what we need to do considering our current implementation.

**Comment by segeeslice** [comment]
Hm... yeah maybe we just need to convert it somehow when storing it so that it doesn't get deleted? Does converting them to the unicode `\u2424` (or just `\n`) work?

Or we could convert one end can convert newlines to something like `<br/>`, which users wouldn't be manually typing anyway.

Definitely gonna be a bit hacky in any case, but if we can't change the JSON encoding itself it may be our only solution
