### ISSUE TITLE
META_StartDate default value

### ISSUE THREAD

**Issue by RobBoeckermann** [RobBoeckermann/Meetify#6]
The table models have the default for META_StartDate set to "datetime.now", but signup() in users.py sets the value to "timezone.now()". What is the difference between the two? Which should we use? And is it required in signup() if a default is set in the model?

**Comment by segeeslice** [comment]
![image](https://user-images.githubusercontent.com/32147527/105861272-8a142b00-5fbc-11eb-956d-87470d49c00e.png)
([From this link](https://stackoverflow.com/questions/26949959/timezone-now-vs-datetime-datetime-now))

**Comment by RobBoeckermann** [comment]
This would be the timezone of the server, correct? We don't want the start dates to differ from user-to-user or a record could show as being created earlier than another just because of the timezone. Could we use UTC for all times in the DB?

**Comment by segeeslice** [comment]
> ...Could we use UTC for all times in the DB?

Yeah that's probably for the best. I assume we'd just need to set it to UTC on the server once and then just use `timezone.now()`? Based on my cursory understanding from the [timezone documentation](https://docs.djangoproject.com/en/3.1/topics/i18n/timezones/)

**Comment by jsteuver** [comment]
The `timezone.now()` in the users.py file is there because when I created the initial table, I didn't give the `META_StartDate` a default value. So that `timezone.now()` call in the users.py file is no longer needed. 

Django has timezone support and is already enabled in our settings.py file (`USE_TZ = True`) and the timezone is already set to UTC (`TIME_ZONE = 'UTC'`), so calling `timezone.now()` from the server side will always give us UTC time, which sounds like that is what we want.

Ultimately I think we should just remove the `timezone.now()` call from the users.py file and change the model to use `timezone.now()` instead of `datetime.now`.
